image: node10
variables:
  NPM_TOKEN: ${NPM_TOKEN}
  NPM_HOST_URL: ''
  GIT_DEPTH: 0
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
stages:
  - test
  - publish

before_script: 
  - npm install

test:
  stage: test
  script:
    - npm run lint
    - npm test

publish:
  stage: publish
  only:
    - release
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm publish
